ALTER SESSION SET CURRENT_SCHEMA = YOON;

ALTER SESSION SET WORKAREA_SIZE_POLICY=MANUAL;

ALTER SESSION SET SORT_AREA_SIZE = 1000000000;

DROP TABLE 주문집계_68;
CREATE TABLE 주문집계_68 AS
SELECT 상품번호, 주문형태, 매장번호, 주문일자,  ROWNUM 주문금액 
FROM (SELECT 'P' || LPAD(LEVEL, 3, '0') 상품번호
      FROM DUAL
      CONNECT BY LEVEL <= 100) A,
     (SELECT 'K' || LPAD(LEVEL, 2, '0') 주문형태
      FROM   DUAL
      CONNECT BY LEVEL <= 10) B,
     (SELECT 'M' || LPAD(LEVEL, 3, '0') 매장번호
      FROM  DUAL
      CONNECT BY LEVEL <= 100) C,
     (SELECT TO_CHAR(TO_DATE('20181231', 'YYYYMMDD') + LEVEL * -1, 'YYYYMMDD') 주문일자
      FROM DUAL 
      CONNECT BY LEVEL <= 100) D 
;

ALTER TABLE 주문집계_68 
ADD CONSTRAINT PK_주문집계_68 PRIMARY KEY(주문형태, 매장번호, 상품번호, 주문일자);

CREATE INDEX IX_주문집계_68 ON 주문집계_68(주문일자, 상품번호);

CREATE PUBLIC SYNONYM 주문집계_68 FOR YOON.주문집계_68;

EXECUTE DBMS_STATS.GATHER_TABLE_STATS('YOON', '주문집계_68');
/*
