DROP TABLE YOON.TAB1;
DROP TABLE YOON.TAB2;
CREATE TABLE YOON.TAB1 AS
  SELECT ROWNUM C1, TO_CHAR(300000-ROWNUM) C2, TO_CHAR(500000-ROWNUM) C3, 1000000-ROWNUM C4,
         'ASDFFDSAASDF' C5
  FROM DUAL
  CONNECT BY LEVEL <= 100000;
  
CREATE TABLE YOON.TAB2 AS
SELECT * FROM YOON.TAB1;

CREATE PUBLIC SYNONYM TAB1 FOR YOON.TAB1;
CREATE PUBLIC SYNONYM TAB2 FOR YOON.TAB2;

CREATE INDEX YOON.TAB1_X1 ON YOON.TAB1(C2);
CREATE INDEX YOON.TAB1_X2 ON YOON.TAB1(C1);
CREATE INDEX YOON.TAB2_X1 ON YOON.TAB2(C1, C4);
CREATE INDEX YOON.TAB2_X2 ON YOON.TAB2(C3, C1);
CREATE INDEX YOON.TAB2_X3 ON YOON.TAB2(C1, C3);
DROP INDEX YOON.TAB2_X2;

ALTER SESSION SET STATISTICS_LEVEL = ALL;

UPDATE TAB1
SET C2 = 'M'
WHERE C1 BETWEEN 21 AND 30;
COMMIT;

UPDATE TAB1
SET C2 = 'C'
WHERE C1 BETWEEN 41 AND 50;
COMMIT;

UPDATE  TAB1 
SET C3 = 'ABC'
WHERE C2 IN ('M', 'C');

COMMIT;