/*
34회  1번
*/

ALTER SESSION SET CURRENT_SCHEMA=YOON;

alter session set workarea_size_policy = manual;
ALTER SESSION SET SORT_AREA_SIZE = 1000000000;

DROP   TABLE 일자임시_70 ;
CREATE TABLE 일자임시_70 AS
SELECT   TO_CHAR(TO_DATE('20170319', 'YYYYMMDD') - LEVEL, 'YYYYMMDD') 날짜
FROM     DUAL CONNECT BY LEVEL <= 138;

DROP TABLE 주문_70;

CREATE  TABLE  주문_70 AS
SELECT  LPAD(TO_CHAR(A.상품ID), 7, '0')          상품ID
      , B.고객번호
      , C.주문일자 
      , TRUNC(DBMS_RANDOM.VALUE(50000, 1000000)) 주문가격
      , 'ASDFFDSAASDFFDSAASDFASDFFDSAASDFFDSAASDFASDFFDSAASDFFDSAASDF' C1
      , 'ASDFFDSAASDFFDSAASDFASDFFDSAASDFFDSAASDFASDFFDSAASDFFDSAASDF' C2
      , 'ASDFFDSAASDFFDSAASDFASDFFDSAASDFFDSAASDFASDFFDSAASDFFDSAASDF' C3
      , 'ASDFFDSAASDFFDSAASDFASDFFDSAASDFFDSAASDFASDFFDSAASDFFDSAASDF' C4
      
FROM    (SELECT LEVEL 상품ID                        FROM DUAL CONNECT BY LEVEL <= 100) A,
        (SELECT 'C' || LPAD(LEVEL, 5, '0') 고객번호 FROM DUAL CONNECT BY LEVEL <= 1000) B,  
        (SELECT 날짜 주문일자                       FROM 일자임시_70     WHERE 날짜 >= '20161208') C
;

ALTER TABLE 주문_70 ADD CONSTRAINT PK_주문_70 PRIMARY KEY(상품ID, 고객번호, 주문일자);

CREATE PUBLIC SYNONYM 주문_70 FOR 주문_70;
      
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('YOON', '주문_70');

SELECT COUNT(*) FROM 주문_70;
SELECT COUNT(주문가격) FROM 주문_70;
