DROP TABLE YOON.CUST_CG_67;
CREATE TABLE YOON.CUST_CG_67
  (  CUST_MD_CD  VARCHAR2(3)
   , CUST_MD_NM  VARCHAR2(50)
   , CUST_CD_DIV VARCHAR2(3)
   , CONSTRAINT PK_CUST_CG_67 PRIMARY KEY(CUST_MD_CD)
  );

CREATE PUBLIC SYNONYM CUST_CG_67 FOR YOON.CUST_CG_67;

INSERT INTO CUST_CG_67
SELECT LPAD(ROWNUM, 3, 0) CUST_MD_CD, LPAD(ROWNUM, 3, 0) || 'ASDFFDSAASDF' CUST_MD_NM, X.CUST_CD_DIV
FROM ( SELECT 'ABC' CUST_CD_DIV FROM DUAL
       UNION ALL
       SELECT 'XXX' CUST_CD_DIV FROM DUAL
       UNION ALL
       SELECT 'YYY' CUST_CD_DIV FROM DUAL
    ) X,
    ( SELECT LEVEL FROM DUAL
      CONNECT BY LEVEL <= 10
    ) Y
;

COMMIT;

DROP TABLE YOON.CUST_67;
CREATE TABLE YOON.CUST_67
  (  CUST_NO     VARCHAR2(7)
   , CUST_NM     VARCHAR2(50)
   , C1          VARCHAR2(50)
   , C2          VARCHAR2(50)
   , C3          VARCHAR2(50)
   , CUST_MD_CD  VARCHAR2(50)
   , CONSTRAINT PK_CUST_67 PRIMARY KEY(CUST_NO)
   );
   
CREATE PUBLIC SYNONYM CUST_67 FOR YOON.CUST_67;

INSERT INTO YOON.CUST_67
SELECT 'C' || LPAD(ROWNUM, 6, 0) CUST_NO, LPAD(ROWNUM, 6, 0) || 'ASDFFDSAASDF'
     , 'FDSLAAJKSDLFFDLSJAASKLDF' C1
     , 'FDSLAAJKSDLFFDLSJAASKLDF' C2
     , 'FDSLAAJKSDLFFDLSJAASKLDF' C3
     , Y.CUST_MD_CD
FROM (SELECT LEVEL FROM DUAL CONNECT BY LEVEL <= 1000) X,
     CUST_CG_67 Y 
;

COMMIT;

DROP TABLE YOON.PROD_CG_67;
CREATE TABLE PROD_CG_67
  (  PROD_MD_CD  VARCHAR2(3)
   , PROD_MD_NM  VARCHAR2(10)
   , CONSTRAINT PK_PROD_CG_67 PRIMARY KEY(PROD_MD_CD)
   );
   
CREATE PUBLIC SYNONYM PROD_CG_67 FOR YOON.PROD_CG_67;

INSERT INTO PROD_CG_67
SELECT '001', '은하수' FROM DUAL
UNION ALL
SELECT '002', '수성' FROM DUAL
UNION ALL
SELECT '003', '금성' FROM DUAL
UNION ALL
SELECT '004', '지구' FROM DUAL
UNION ALL
SELECT '005', '화성' FROM DUAL
;

COMMIT;

DROP TABLE YOON.PROD_67;
CREATE TABLE YOON.PROD_67
   (  PROD_NO     VARCHAR2(4)
    , PROD_NM     VARCHAR2(50)
    , PROD_MD_CD  VARCHAR2(3)
    , CONSTRAINT PK_PROD_67 PRIMARY KEY(PROD_NO)
    );
    
CREATE PUBLIC SYNONYM PROD_67 FOR YOON.PROD_67;

INSERT INTO PROD_67
SELECT 'P' || LPAD(ROWNUM, 3, 0) PROD_NO, 'P' || LPAD(ROWNUM, 3, 0) || Y.PROD_MD_NM PROD_NM, Y.PROD_MD_CD
FROM (SELECT ROWNUM FROM DUAL CONNECT BY LEVEL <= 10) X, PROD_CG_67 Y
;

COMMIT;

DROP TABLE YOON.ORDER_CG_67;
CREATE TABLE YOON.ORDER_CG_67
   (  ORDER_MD_CD  VARCHAR2(3)
    , ORDER_MD_NM  VARCHAR2(50)
    , CONSTRAINT PK_ORDER_CG_67 PRIMARY KEY(ORDER_MD_CD)
    );
    
CREATE PUBLIC SYNONYM ORDER_CG_67 FOR YOON.ORDER_CG_67;

INSERT INTO ORDER_CG_67
SELECT LPAD(ROWNUM, 3, 0) ORDER_MD_CD, LPAD(ROWNUM, 2, 0) || 'ASDFFDSAASDF' ORDER_MD_NM
FROM DUAL 
CONNECT BY LEVEL <= 100
;

COMMIT;

DROP TABLE YOON.ORDER_67;
CREATE TABLE YOON.ORDER_67
  (  ORDER_NO    VARCHAR2(8)
   , CUST_NO     VARCHAR2(7)
   , PROD_NO     VARCHAR2(4)
   , ORDER_DT    VARCHAR2(8)
   , ORDER_MD_CD VARCHAR2(3)
   , QTY         NUMBER
   , AMT         NUMBER
   , CONSTRAINT PK_ORDER_67 PRIMARY KEY(ORDER_NO)
   );

CREATE PUBLIC SYNONYM ORDER_67 FOR YOON.ORDER_67;

INSERT INTO ORDER_67
SELECT 'O'|| LPAD(ROWNUM, 7, 0) ORDER_NO
     , C.CUST_NO, P.PROD_NO 
     , TO_CHAR(TO_DATE('20180101' , 'YYYYMMDD') +  LPAD(MOD(ROWNUM, 600)+1, 3, 0), 'YYYYMMDD') ORDER_DT
     , LPAD(TRUNC(DBMS_RANDOM.VALUE(1, 100)), 3, 0) ORDER_MD_CD
     , MOD(ROWNUM, 5) + 1
     , TRUNC(DBMS_RANDOM.VALUE(10000, 50000))
FROM CUST_67 C, PROD_67 P 
;

COMMIT;


SELECT COUNT(*) FROM CUST_CG_67;
SELECT COUNT(*) FROM CUST_67;

--1,500,000
SELECT COUNT(*) FROM ORDER_67;
SELECT COUNT(*) FROM ORDER_CG_67;
--100

--50
SELECT COUNT(*) FROM PROD_67;
SELECT COUNT(*) FROM PROD_CG_67;
--5