DROP TABLE YOON.T_CUST52;
CREATE TABLE YOON.T_CUST52
 (  CUST_NO     VARCHAR2(10),
   CUST_NM     VARCHAR2(50),
   JUMIN_NO    VARCHAR2(13),
  CONSTRAINT PK_T_CUST  PRIMARY KEY(CUST_NO)
 );

CREATE PUBLIC SYNONYM T_CUST52 FOR YOON.T_CUST52;

INSERT /*+ APPEND */ INTO T_CUST52
SELECT LPAD(TO_CHAR(ROWNUM), 10, '0') CUST_NO
     , LPAD(TO_CHAR(ROUND(DBMS_RANDOM.VALUE(1, 900000))), 10, '0') CUST_NM
     , LPAD(TO_CHAR(ROWNUM), 13, '0') JUMIN_NO     
FROM DUAL
CONNECT BY LEVEL <= 1000000
ORDER BY DBMS_RANDOM.RANDOM()
;

COMMIT;

DROP TABLE YOON.T_CONT52;
CREATE TABLE YOON.T_CONT52
  ( CONT_NO    VARCHAR2(10),
   CONT_DT     DATE,
   TERMI_DT     DATE,
   TERMI_AMT   NUMBER,
   CUST_NO     VARCHAR2(10),
CONSTRAINT PK_T_CONT52 PRIMARY KEY(CONT_NO)
 );

CREATE PUBLIC SYNONYM T_CONT52 FOR YOON.T_CONT52;

DROP TABLE YOON.T_DATE;
CREATE TABLE YOON.T_DATE AS
SELECT TO_CHAR(SYSDATE - ROWNUM, 'YYYYMMDD') CONT_DT
FROM DUAL CONNECT BY LEVEL <= 1000;

INSERT /*+ APPEND */ INTO T_CONT52
SELECT LPAD(TO_CHAR(ROWNUM), 10, '0') CONT_NO
     , TO_DATE(CONT_DT) CONT_DT
     , TO_DATE(CONT_DT) + 7 TEMI_DT
     , DECODE(ROUND(MOD(ROWNUM, 10)), 0 , 3, ROUND(MOD(ROWNUM, 10))) TERMI_AMT
     , LPAD(TO_CHAR(ROUND(DBMS_RANDOM.VALUE(1, 500000))), 10, '0') CUST_NO
FROM YOON.T_DATE A,
     (SELECT ROWNUM R_NUM FROM DUAL CONNECT BY LEVEL <= 1000) B
ORDER BY DBMS_RANDOM.RANDOM();

COMMIT;
