/*
해설)
  - INSERT SELECT  이후  UPDATE를  => TAB_X_66, TAB_Y_66를 조인하여 UPDATE문을 생략
  - REDO LOG에 LOGGING을 최소화 하기 위해 TAB_66 테이블을 NOLOGGING 으로 변경
  - INSERT 문을 DIRECT PATH INSERT로 변경
*/

ALTER TABLE YOON.TAB_66 NOLOGGING;

ALTER TABLE YOON.TAB_66 
DROP CONSTRAINT PK_TAB_66;

INSERT /*+ APPEND */ INTO TAB_66 
SELECT /*+ FULL(X) FULL(Y) USE_HASH(Y) */
       X.C1, X.C2, X.C3, X.C4
     , Y.C5
FROM TAB_X_66 X,  TAB_Y_66 Y
WHERE X.C1 = Y.C1 (+)
 AND  C1.C4(+) <> 'KK';

COMMIT;

ALTER TABLE YOON.TAB_66
ADD CONSTRAINT PK_TAB_66 PRIMARY KEY(C1, C2);